server:
  port: 5003

spring:
  application:
    name: TASK-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/task-submission-service
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver
