server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/task-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
